name: Generate Doxygen Documentation

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Create Working Directory
          run: mkdir ./docs/out
        - name: Generate Documentation
          uses: mattnotmitt/doxygen-action@1.9.5
          with:
            doxyfile-path: ./docs/Doxyfile
            working-directory: ./docs/out
        - name: Deploy on GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          # if: github.ref == 'refs/heads/stable'
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./docs/out
